//! Raw FFI bindings to the VRobots SDK C library, `vrobots_sdk_capi`.
//!
//! This crate declares the C API exactly as the header `vrobots_sdk.h`
//! declares it: the `vrsdk_*` functions, the `VRSDK_*` constants and the
//! `#[repr(C)]` structs. The declarations are the `bindings.rs` that ships in
//! the C bundle of the matching release, generated by bindgen from that header.
//! Every function is `unsafe` and follows the C rules documented on it. Most
//! programs should depend on the safe wrapper crate `vrobots-sdk` instead.
//!
//! ```no_run
//! use std::ffi::CStr;
//!
//! // SAFETY: `vrsdk_version` returns a static, NUL-terminated string.
//! let version = unsafe { CStr::from_ptr(vrobots_sdk_sys::vrsdk_version()) };
//! println!("vrobots_sdk_capi {}", version.to_string_lossy());
//! ```
//!
//! # Where the C library comes from
//!
//! The build script downloads the C bundle whose version equals this crate's
//! version from the GitHub Release `v<version>` of
//! <https://github.com/ubicoders/vrobots-sdk>, together with the Release's
//! `SHA256SUMS`:
//!
//! | Target | Asset |
//! |---|---|
//! | x86_64 Linux, glibc 2.28 or newer | `vrobots_sdk-cpp-<version>-linux-x86_64.tar.gz` |
//! | x86_64 Windows, MSVC | `vrobots_sdk-cpp-<version>-windows-x86_64.zip` |
//!
//! The build fails if the bundle's SHA-256 differs from the one `SHA256SUMS`
//! lists, or if `SHA256SUMS` does not list it. A verified bundle is unpacked
//! into the build directory and reused by later builds without network access
//! until `cargo clean` removes it. The download uses HTTPS through rustls with
//! the bundled Mozilla root certificates (no OpenSSL) and honours
//! `HTTPS_PROXY`, `HTTP_PROXY`, `ALL_PROXY` and `NO_PROXY`.
//!
//! # Building without the download
//!
//! Set `VROBOTS_SDK_DIR` to the folder of an unpacked C bundle: for offline
//! builds, on networks that re-sign TLS traffic with their own certificate, and
//! for targets without a published bundle. The folder must hold `bindings.rs`
//! at its root and the library in `lib/`: `libvrobots_sdk_capi.so` on Linux,
//! `vrobots_sdk_capi.dll.lib` (and `vrobots_sdk_capi.dll` to run) on Windows,
//! or the static library with the `static` feature. The bundle must be the
//! one of this crate's version, because `bindings.rs` describes exactly that
//! library. Use an absolute path; a relative one is resolved against this
//! crate's directory.
//!
//! `VROBOTS_SDK_DOWNLOAD_URL` replaces the URL prefix
//! `https://github.com/ubicoders/vrobots-sdk/releases/download/v<version>`,
//! for a mirror that serves the same bundle and `SHA256SUMS`.
//!
//! # Linking and running
//!
//! By default the crate links the shared library, which must be found again
//! when the program starts:
//!
//! - **Linux**: `libvrobots_sdk_capi.so` must be on the program's rpath or on
//!   `LD_LIBRARY_PATH`. The build script adds an rpath to the bundle's `lib/`
//!   folder, but Cargo applies it only to this crate's own tests, examples and
//!   binaries, never to a dependent's program.
//! - **Windows**: `vrobots_sdk_capi.dll` must sit beside the executable or in
//!   a folder on `PATH`.
//!
//! `cargo run` and `cargo test` find a downloaded bundle on their own, because
//! Cargo adds library folders inside the target directory to `PATH` or
//! `LD_LIBRARY_PATH`. They do not do this for a folder named by
//! `VROBOTS_SDK_DIR`, which lies outside the target directory; add its `lib/`
//! folder to `LD_LIBRARY_PATH` or `PATH` yourself. To ship a program, copy the
//! shared library next to it (with an `$ORIGIN` rpath on Linux).
//!
//! The `static` feature links the static library instead, so the program
//! needs no shared library at run time. On Linux the system libraries it uses
//! are the ones every Rust program already links. On Windows the static link
//! has not been tested yet and may need further system import libraries.
//!
//! A build script of a crate that depends on this one directly receives
//! `DEP_VROBOTS_SDK_CAPI_LIB_DIR` (the bundle's `lib/` folder, for copying the
//! shared library), `DEP_VROBOTS_SDK_CAPI_BUNDLE_DIR` (the bundle root) and
//! `DEP_VROBOTS_SDK_CAPI_INCLUDE` (the C and C++ headers), except in
//! documentation builds.
//!
//! # Documentation builds
//!
//! docs.rs builds crates without network access, so it cannot download the C
//! bundle. When the environment variable `DOCS_RS` is set and not empty, as it
//! is on docs.rs, the build script downloads nothing, ignores
//! `VROBOTS_SDK_DIR` and links nothing. It compiles `bindings/vrobots_sdk.rs`
//! instead: a copy of the bundle's `bindings.rs` that ships inside this crate
//! for documentation builds only. `cargo doc` and `cargo check` work in this
//! mode, for this crate and for crates that depend on it, but anything that
//! calls the library fails to link, so leave `DOCS_RS` unset for ordinary
//! builds. A dependent's build script that uses the `DEP_VROBOTS_SDK_CAPI_*`
//! values should skip that work when `DOCS_RS` is set.
//!
//! Every other build compiles the bundle's own `bindings.rs`. This crate's
//! tests compare the shipped copy with it byte for byte and fail when the two
//! differ.
//!
//! # Licence
//!
//! The VRobots SDK, including this crate and the C library it links, is
//! released under the Creative Commons Attribution-NonCommercial-ShareAlike 4.0
//! International licence (CC BY-NC-SA 4.0) with a patent addendum. The full
//! texts are included in this crate as `LICENSE` and `LICENSE-ADDENDUM`, and
//! are also at the root of <https://github.com/ubicoders/vrobots-sdk>.

#![allow(non_upper_case_globals, non_camel_case_types, non_snake_case)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
