[package]
name = "vrobots-sdk"
version = "0.1.10"
edition = "2021"
description = "Rust client SDK for the Ubicoders virtual robots simulator"
repository = "https://github.com/ubicoders/vrobots-sdk"
license = "CC-BY-NC-SA-4.0"

[dependencies]
vrobots-sdk-sys = { path = "../vrobots-sdk-sys", version = "0.1.10" }
