//! Tests of the build script's archive handling, on archives laid out like the
//! published C bundles: files at the archive root, no top-level folder.

// The build script uses items that these tests do not.
#[allow(dead_code)]
#[path = "../build/support.rs"]
mod support;
#[path = "../build/unpack.rs"]
mod unpack;

use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};

use support::ArchiveKind;

const HEADER: &[u8] = b"/* vrobots_sdk.h */\n";
const BINDINGS: &[u8] = b"/* automatically generated by rust-bindgen */\n";
const LIBRARY: &[u8] = b"\x7fELF not really a library, but compressible bytes bytes bytes bytes";

/// A fresh, empty scratch folder under Cargo's per-package temporary directory.
fn scratch_dir(name: &str) -> PathBuf {
    let dir = PathBuf::from(env!("CARGO_TARGET_TMPDIR")).join(name);
    let _ = fs::remove_dir_all(&dir);
    fs::create_dir_all(&dir).unwrap();
    dir
}

fn assert_file(root: &Path, relative: &str, contents: &[u8]) {
    let path = root.join(relative);
    assert_eq!(fs::read(&path).unwrap(), contents, "{}", path.display());
}

/// Writes a `.tar.gz` the way `tar -czf <archive> -C <staging> .` does: every
/// entry is prefixed with `./`, and the root folder itself is an entry.
fn write_tar_gz(path: &Path, files: &[(&str, &[u8])]) {
    let file = fs::File::create(path).unwrap();
    let encoder = flate2::write::GzEncoder::new(file, flate2::Compression::default());
    let mut builder = tar::Builder::new(encoder);
    for dir in ["./", "./include/", "./lib/"] {
        let mut header = tar::Header::new_gnu();
        header.set_entry_type(tar::EntryType::Directory);
        header.set_mode(0o755);
        header.set_size(0);
        builder.append_data(&mut header, dir, &[][..]).unwrap();
    }
    for (name, contents) in files {
        let mut header = tar::Header::new_gnu();
        header.set_mode(0o644);
        header.set_size(contents.len() as u64);
        builder
            .append_data(&mut header, format!("./{name}"), *contents)
            .unwrap();
    }
    builder.into_inner().unwrap().finish().unwrap();
}

/// Writes a deflate-compressed `.zip` with explicit directory entries, which is
/// what 7-Zip produces for `7z a -tzip <archive> .`.
fn write_zip(path: &Path, files: &[(&str, &[u8])]) {
    let file = fs::File::create(path).unwrap();
    let mut zip = zip::ZipWriter::new(file);
    let options = zip::write::SimpleFileOptions::default()
        .compression_method(zip::CompressionMethod::Deflated);
    for dir in ["include/", "lib/"] {
        zip.add_directory(dir, options).unwrap();
    }
    for (name, contents) in files {
        zip.start_file(*name, options).unwrap();
        zip.write_all(contents).unwrap();
    }
    zip.finish().unwrap();
}

#[test]
fn unpacks_a_linux_style_tar_gz_into_the_bundle_root() {
    let dir = scratch_dir("unpack-tar-gz");
    let archive = dir.join("vrobots_sdk-cpp-0.0.0-linux-x86_64.tar.gz");
    write_tar_gz(
        &archive,
        &[
            ("include/vrobots_sdk.h", HEADER),
            ("lib/libvrobots_sdk_capi.so", LIBRARY),
            ("bindings.rs", BINDINGS),
        ],
    );

    let bundle = dir.join("bundle");
    unpack::unpack(&archive, ArchiveKind::TarGz, &bundle).unwrap();
    assert_file(&bundle, "include/vrobots_sdk.h", HEADER);
    assert_file(&bundle, "lib/libvrobots_sdk_capi.so", LIBRARY);
    assert_file(&bundle, "bindings.rs", BINDINGS);
}

#[test]
fn unpacks_a_windows_style_zip_into_the_bundle_root() {
    let dir = scratch_dir("unpack-zip");
    let archive = dir.join("vrobots_sdk-cpp-0.0.0-windows-x86_64.zip");
    write_zip(
        &archive,
        &[
            ("include/vrobots_sdk.h", HEADER),
            ("lib/vrobots_sdk_capi.dll", LIBRARY),
            ("lib/vrobots_sdk_capi.dll.lib", LIBRARY),
            ("lib/vrobots_sdk_capi.lib", LIBRARY),
            ("bindings.rs", BINDINGS),
        ],
    );

    let bundle = dir.join("bundle");
    unpack::unpack(&archive, ArchiveKind::Zip, &bundle).unwrap();
    assert_file(&bundle, "include/vrobots_sdk.h", HEADER);
    assert_file(&bundle, "lib/vrobots_sdk_capi.dll.lib", LIBRARY);
    assert_file(&bundle, "lib/vrobots_sdk_capi.lib", LIBRARY);
    assert_file(&bundle, "bindings.rs", BINDINGS);
}

#[test]
fn reports_an_archive_that_is_not_one() {
    let dir = scratch_dir("unpack-garbage");
    let archive = dir.join("garbage.bin");
    fs::write(&archive, b"this is not an archive").unwrap();
    assert!(unpack::unpack(&archive, ArchiveKind::TarGz, &dir.join("a")).is_err());
    assert!(unpack::unpack(&archive, ArchiveKind::Zip, &dir.join("b")).is_err());
    let missing = dir.join("missing.zip");
    let err = unpack::unpack(&missing, ArchiveKind::Zip, &dir.join("c")).unwrap_err();
    assert!(err.starts_with("cannot open"), "{err}");
}
